Algoritmo "Idadese"
// 
//  
// Descrição   : exemplo com SE
// Autor(a)    : Luiz Fabio
// Aula ministrada por: Prof Franklin Portela
// Data atual  : 15/03/2024
Var
// Seção de Declarações das variáveis 
    idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreval("Digite a idade: ")
     Leia (idade)
     se((idade > 17) e (idade <60))entao
       Escreval(idade)
     Fimse

Fimalgoritmo